// DO NOT EDIT.
// code generated by goenums v0.4.3 at Jul  3 19:10:53.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f log_type.go

package logtype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// LogType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type LogType struct {
	logType
}

// logTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the LogType type.
type logTypesContainer struct {
	UNKNOWN LogType
	LOGRUS  LogType
	NOOP    LogType
}

// LogTypes is a main entry point using the LogType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var LogTypes = logTypesContainer{
	UNKNOWN: LogType{
		logType: unknown,
	},
	LOGRUS: LogType{
		logType: logrus,
	},
	NOOP: LogType{
		logType: noop,
	},
}

// invalidLogType is an invalid sentinel value for LogType
var invalidLogType = LogType{
	logType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logTypesContainer) allSlice() []LogType {
	return []LogType{
		LogTypes.LOGRUS,
		LogTypes.NOOP,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l logTypesContainer) All() iter.Seq[LogType] {
	return func(yield func(LogType) bool) {
		for _, v := range l.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseLogType = errors.New("invalid input provided to parse to LogType")

// ParseLogType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseLogType(input any) (LogType, error) {
	switch v := input.(type) {
	case LogType:
		return v, nil
	case string:
		if result := stringToLogType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToLogType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToLogType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToLogType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidLogType, fmt.Errorf("invalid type %T", input)
	}
	return invalidLogType, fmt.Errorf("%w: invalid value %v", ErrParseLogType, input)
}

// logTypesNameMap is a map of enum values to their LogType representation
// It is used to convert string representations of enum values into their LogType representation.
var logTypesNameMap = map[string]LogType{
	"unknown": LogTypes.UNKNOWN,
	"logrus":  LogTypes.LOGRUS,
	"noop":    LogTypes.NOOP,
}

// stringToLogType converts a string representation of an enum value into its LogType representation
// It returns a pointer to the LogType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToLogType(s string) *LogType {
	if t, ok := logTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToLogType converts a numeric value to a LogType
// It returns a pointer to the LogType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToLogType[T constraints.Integer | constraints.Float](num T) *LogType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(LogTypes.allSlice()) {
		return nil
	}
	result := LogTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveLogTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveLogTypes(f func(LogType)) {
	for _, p := range LogTypes.allSlice() {
		f(p)
	}
}

// validLogTypes is a map of enum values to their validity
var validLogTypes = map[LogType]bool{
	LogTypes.UNKNOWN: false,
	LogTypes.LOGRUS:  true,
	LogTypes.NOOP:    true,
}

// IsValid checks whether the LogTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (l LogType) IsValid() bool {
	return validLogTypes[l]
}

// MarshalJSON implements the json.Marshaler interface for LogType.
// It returns the JSON representation of the enum value as a byte slice.
func (l LogType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for LogType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (l *LogType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newl, err := ParseLogType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for LogType.
// It returns the string representation of the enum value as a byte slice
func (l LogType) MarshalText() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LogType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogType) UnmarshalText(b []byte) error {
	newl, err := ParseLogType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Scan implements the database/sql.Scanner interface for LogType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (l *LogType) Scan(value any) error {
	newl, err := ParseLogType(value)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Value implements the database/sql/driver.Valuer interface for LogType.
// It returns the string representation of the enum value.
func (l LogType) Value() (driver.Value, error) {
	return l.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for LogType.
// It returns the binary representation of the enum value as a byte slice.
func (l LogType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for LogType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LogType) UnmarshalBinary(b []byte) error {
	newl, err := ParseLogType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for LogType.
// It returns the string representation of the enum value.
func (l LogType) MarshalYAML() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (l *LogType) UnmarshalYAML(b []byte) error {
	newl, err := ParseLogType(b)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// logtypeNames is a constant string slice containing all enum values cononical absolute names
const logtypeNames = "unknownlogrusnoop"

// logtypeNamesMap is a map of enum values to their canonical absolute
// name positions within the logtypeNames string slice
var logtypeNamesMap = map[LogType]string{
	LogTypes.UNKNOWN: logtypeNames[0:7],
	LogTypes.LOGRUS:  logtypeNames[7:13],
	LogTypes.NOOP:    logtypeNames[13:17],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (l LogType) String() string {
	if str, ok := logtypeNamesMap[l]; ok {
		return str
	}
	return fmt.Sprintf("logtype(%d)", l.logType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[unknown]
	_ = x[logrus-1]
	_ = x[noop-2]
}
