// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ApplicationInfrastructure is an autogenerated mock type for the ApplicationInfrastructure type
type ApplicationInfrastructure struct {
	mock.Mock
}

// ConfigureInfrastructure provides a mock function with no fields
func (_m *ApplicationInfrastructure) ConfigureInfrastructure() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigureInfrastructure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApplicationInfrastructure creates a new instance of ApplicationInfrastructure. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationInfrastructure(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationInfrastructure {
	mock := &ApplicationInfrastructure{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
