// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	contracts "frisboo-bank/pkg/application/contracts"
	containercontracts "frisboo-bank/pkg/container/contracts"

	decorator "frisboo-bank/pkg/container/dependencies/decorator"

	environment "frisboo-bank/pkg/environment"

	loggercontracts "frisboo-bank/pkg/logger/contracts"

	mock "github.com/stretchr/testify/mock"

	module "frisboo-bank/pkg/container/dependencies/module"

	provider "frisboo-bank/pkg/container/dependencies/provider"
)

// ApplicationBuilder is an autogenerated mock type for the ApplicationBuilder type
type ApplicationBuilder struct {
	mock.Mock
}

// Build provides a mock function with no fields
func (_m *ApplicationBuilder) Build() contracts.Application {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 contracts.Application
	if rf, ok := ret.Get(0).(func() contracts.Application); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Application)
		}
	}

	return r0
}

// Container provides a mock function with no fields
func (_m *ApplicationBuilder) Container() containercontracts.Container {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Container")
	}

	var r0 containercontracts.Container
	if rf, ok := ret.Get(0).(func() containercontracts.Container); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(containercontracts.Container)
		}
	}

	return r0
}

// Decorators provides a mock function with no fields
func (_m *ApplicationBuilder) Decorators() []decorator.Decorator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Decorators")
	}

	var r0 []decorator.Decorator
	if rf, ok := ret.Get(0).(func() []decorator.Decorator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]decorator.Decorator)
		}
	}

	return r0
}

// Environment provides a mock function with no fields
func (_m *ApplicationBuilder) Environment() environment.Environment {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Environment")
	}

	var r0 environment.Environment
	if rf, ok := ret.Get(0).(func() environment.Environment); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(environment.Environment)
	}

	return r0
}

// Logger provides a mock function with no fields
func (_m *ApplicationBuilder) Logger() loggercontracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 loggercontracts.Logger
	if rf, ok := ret.Get(0).(func() loggercontracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loggercontracts.Logger)
		}
	}

	return r0
}

// Modules provides a mock function with no fields
func (_m *ApplicationBuilder) Modules() []module.Module {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modules")
	}

	var r0 []module.Module
	if rf, ok := ret.Get(0).(func() []module.Module); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]module.Module)
		}
	}

	return r0
}

// ProvideModule provides a mock function with given fields: modules
func (_m *ApplicationBuilder) ProvideModule(modules ...module.Module) {
	_va := make([]interface{}, len(modules))
	for _i := range modules {
		_va[_i] = modules[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Providers provides a mock function with no fields
func (_m *ApplicationBuilder) Providers() []provider.Provider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 []provider.Provider
	if rf, ok := ret.Get(0).(func() []provider.Provider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Provider)
		}
	}

	return r0
}

// NewApplicationBuilder creates a new instance of ApplicationBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationBuilder {
	mock := &ApplicationBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
