// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	hook "frisboo-bank/pkg/container/dependencies/hook"
	contracts "frisboo-bank/pkg/logger/contracts"

	invoker "frisboo-bank/pkg/container/dependencies/invoker"

	mock "github.com/stretchr/testify/mock"
)

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// Logger provides a mock function with no fields
func (_m *Application) Logger() contracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 contracts.Logger
	if rf, ok := ret.Get(0).(func() contracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Logger)
		}
	}

	return r0
}

// RegisterHook provides a mock function with given fields: _a0
func (_m *Application) RegisterHook(_a0 hook.Hooks) {
	_m.Called(_a0)
}

// ResolveFunc provides a mock function with given fields: _a0
func (_m *Application) ResolveFunc(_a0 invoker.Invoker) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields: ctx
func (_m *Application) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: ctx
func (_m *Application) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApplication creates a new instance of Application. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *Application {
	mock := &Application{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
