// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CallbackFn is an autogenerated mock type for the CallbackFn type
type CallbackFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: args
func (_m *CallbackFn) Execute(args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCallbackFn creates a new instance of CallbackFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCallbackFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *CallbackFn {
	mock := &CallbackFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
