// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CleanupFunc is an autogenerated mock type for the CleanupFunc type
type CleanupFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *CleanupFunc) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCleanupFunc creates a new instance of CleanupFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCleanupFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CleanupFunc {
	mock := &CleanupFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
