// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	environment "frisboo-bank/pkg/environment"

	mock "github.com/stretchr/testify/mock"
)

// ConfigLoader is an autogenerated mock type for the ConfigLoader type
type ConfigLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: env, cfg
func (_m *ConfigLoader) Load(env environment.Environment, cfg interface{}) error {
	ret := _m.Called(env, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(environment.Environment, interface{}) error); ok {
		r0 = rf(env, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadByKey provides a mock function with given fields: key, env, cfg
func (_m *ConfigLoader) LoadByKey(key string, env environment.Environment, cfg interface{}) error {
	ret := _m.Called(key, env, cfg)

	if len(ret) == 0 {
		panic("no return value specified for LoadByKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, environment.Environment, interface{}) error); ok {
		r0 = rf(key, env, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigLoader creates a new instance of ConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigLoader {
	mock := &ConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
