// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	decorator "frisboo-bank/pkg/container/dependencies/decorator"

	mock "github.com/stretchr/testify/mock"

	options "frisboo-bank/pkg/options"
)

// Decorator is an autogenerated mock type for the Decorator type
type Decorator struct {
	mock.Mock
}

// Constructor provides a mock function with no fields
func (_m *Decorator) Constructor() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Constructor")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// IsDependency provides a mock function with no fields
func (_m *Decorator) IsDependency() {
	_m.Called()
}

// Options provides a mock function with no fields
func (_m *Decorator) Options() []options.OptionFn[decorator.Config] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 []options.OptionFn[decorator.Config]
	if rf, ok := ret.Get(0).(func() []options.OptionFn[decorator.Config]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.OptionFn[decorator.Config])
		}
	}

	return r0
}

// NewDecorator creates a new instance of Decorator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecorator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Decorator {
	mock := &Decorator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
