// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DefaultFn is an autogenerated mock type for the DefaultFn type
type DefaultFn[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with no fields
func (_m *DefaultFn[T]) Execute() *T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *T
	if rf, ok := ret.Get(0).(func() *T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	return r0
}

// NewDefaultFn creates a new instance of DefaultFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefaultFn[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *DefaultFn[T] {
	mock := &DefaultFn[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
