// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// E is an autogenerated mock type for the E type
type E struct {
	mock.Mock
}

// Details provides a mock function with no fields
func (_m *E) Details() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Details")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Error provides a mock function with no fields
func (_m *E) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StackTrace provides a mock function with no fields
func (_m *E) StackTrace() []uintptr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StackTrace")
	}

	var r0 []uintptr
	if rf, ok := ret.Get(0).(func() []uintptr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uintptr)
		}
	}

	return r0
}

// NewE creates a new instance of E. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewE(t interface {
	mock.TestingT
	Cleanup(func())
}) *E {
	mock := &E{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
