// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	reflection "frisboo-bank/pkg/reflection"
	iter "iter"

	mock "github.com/stretchr/testify/mock"
)

// EnumContainer is an autogenerated mock type for the EnumContainer type
type EnumContainer[T reflection.EnumValue] struct {
	mock.Mock
}

// All provides a mock function with no fields
func (_m *EnumContainer[T]) All() iter.Seq[T] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 iter.Seq[T]
	if rf, ok := ret.Get(0).(func() iter.Seq[T]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[T])
		}
	}

	return r0
}

// NewEnumContainer creates a new instance of EnumContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnumContainer[T reflection.EnumValue](t interface {
	mock.TestingT
	Cleanup(func())
}) *EnumContainer[T] {
	mock := &EnumContainer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
