// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	contracts "frisboo-bank/pkg/logger/contracts"

	mock "github.com/stretchr/testify/mock"
)

// HealthEndpoint is an autogenerated mock type for the HealthEndpoint type
type HealthEndpoint struct {
	mock.Mock
}

// Logger provides a mock function with no fields
func (_m *HealthEndpoint) Logger() contracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 contracts.Logger
	if rf, ok := ret.Get(0).(func() contracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Logger)
		}
	}

	return r0
}

// RegisterEndpoints provides a mock function with no fields
func (_m *HealthEndpoint) RegisterEndpoints() {
	_m.Called()
}

// NewHealthEndpoint creates a new instance of HealthEndpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthEndpoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthEndpoint {
	mock := &HealthEndpoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
