// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	loggercontracts "frisboo-bank/pkg/logger/contracts"

	mock "github.com/stretchr/testify/mock"
)

// HealthServiceCheck is an autogenerated mock type for the HealthServiceCheck type
type HealthServiceCheck struct {
	mock.Mock
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *HealthServiceCheck) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetServiceName provides a mock function with no fields
func (_m *HealthServiceCheck) GetServiceName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServiceName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Logger provides a mock function with no fields
func (_m *HealthServiceCheck) Logger() loggercontracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 loggercontracts.Logger
	if rf, ok := ret.Get(0).(func() loggercontracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loggercontracts.Logger)
		}
	}

	return r0
}

// NewHealthServiceCheck creates a new instance of HealthServiceCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthServiceCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthServiceCheck {
	mock := &HealthServiceCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
