// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	contracts "frisboo-bank/pkg/health/contracts"
	loggercontracts "frisboo-bank/pkg/logger/contracts"

	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// AddServices provides a mock function with given fields: services
func (_m *HealthService) AddServices(services ...contracts.HealthServiceCheck) {
	_va := make([]interface{}, len(services))
	for _i := range services {
		_va[_i] = services[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *HealthService) CheckHealth(ctx context.Context) contracts.CheckAllStatus {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 contracts.CheckAllStatus
	if rf, ok := ret.Get(0).(func(context.Context) contracts.CheckAllStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.CheckAllStatus)
		}
	}

	return r0
}

// Logger provides a mock function with no fields
func (_m *HealthService) Logger() loggercontracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 loggercontracts.Logger
	if rf, ok := ret.Get(0).(func() loggercontracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loggercontracts.Logger)
		}
	}

	return r0
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
