// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	hook "frisboo-bank/pkg/container/dependencies/hook"

	mock "github.com/stretchr/testify/mock"

	options "frisboo-bank/pkg/options"
)

// Hooks is an autogenerated mock type for the Hooks type
type Hooks struct {
	mock.Mock
}

// IsDependency provides a mock function with no fields
func (_m *Hooks) IsDependency() {
	_m.Called()
}

// Options provides a mock function with no fields
func (_m *Hooks) Options() []options.OptionFn[hook.Config] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 []options.OptionFn[hook.Config]
	if rf, ok := ret.Get(0).(func() []options.OptionFn[hook.Config]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.OptionFn[hook.Config])
		}
	}

	return r0
}

// StartConstructor provides a mock function with no fields
func (_m *Hooks) StartConstructor() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartConstructor")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// StopConstructor provides a mock function with no fields
func (_m *Hooks) StopConstructor() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopConstructor")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// NewHooks creates a new instance of Hooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hooks {
	mock := &Hooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
