// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	contracts "frisboo-bank/pkg/http/http_server/contracts"
	httpservertype "frisboo-bank/pkg/http/http_server/enums/http_server_type"

	loggercontracts "frisboo-bank/pkg/logger/contracts"

	mock "github.com/stretchr/testify/mock"
)

// HTTPServerAdapter is an autogenerated mock type for the HTTPServerAdapter type
type HTTPServerAdapter struct {
	mock.Mock
}

// AddMiddlewares provides a mock function with given fields: middlewares
func (_m *HTTPServerAdapter) AddMiddlewares(middlewares ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, middlewares...)
	_m.Called(_ca...)
}

// ListRoutes provides a mock function with no fields
func (_m *HTTPServerAdapter) ListRoutes() []interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListRoutes")
	}

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// Logger provides a mock function with no fields
func (_m *HTTPServerAdapter) Logger() loggercontracts.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 loggercontracts.Logger
	if rf, ok := ret.Get(0).(func() loggercontracts.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loggercontracts.Logger)
		}
	}

	return r0
}

// RouteBuilder provides a mock function with no fields
func (_m *HTTPServerAdapter) RouteBuilder() contracts.RouteBuilder {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RouteBuilder")
	}

	var r0 contracts.RouteBuilder
	if rf, ok := ret.Get(0).(func() contracts.RouteBuilder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.RouteBuilder)
		}
	}

	return r0
}

// SetupDefaultMiddlewares provides a mock function with no fields
func (_m *HTTPServerAdapter) SetupDefaultMiddlewares() {
	_m.Called()
}

// Start provides a mock function with given fields: ctx
func (_m *HTTPServerAdapter) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: ctx
func (_m *HTTPServerAdapter) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Type provides a mock function with no fields
func (_m *HTTPServerAdapter) Type() httpservertype.HttpServerType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 httpservertype.HttpServerType
	if rf, ok := ret.Get(0).(func() httpservertype.HttpServerType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(httpservertype.HttpServerType)
	}

	return r0
}

// NewHTTPServerAdapter creates a new instance of HTTPServerAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPServerAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPServerAdapter {
	mock := &HTTPServerAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
