// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	httperrorresponse "frisboo-bank/pkg/http/responses/http_error_response"

	mock "github.com/stretchr/testify/mock"
)

// HTTPErrorResponseBuilder is an autogenerated mock type for the HTTPErrorResponseBuilder type
type HTTPErrorResponseBuilder struct {
	mock.Mock
}

// AddDetail provides a mock function with given fields: key, value
func (_m *HTTPErrorResponseBuilder) AddDetail(key string, value interface{}) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for AddDetail")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(string, interface{}) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// Build provides a mock function with no fields
func (_m *HTTPErrorResponseBuilder) Build() *httperrorresponse.HTTPErrorResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *httperrorresponse.HTTPErrorResponse
	if rf, ok := ret.Get(0).(func() *httperrorresponse.HTTPErrorResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httperrorresponse.HTTPErrorResponse)
		}
	}

	return r0
}

// SetCode provides a mock function with given fields: code
func (_m *HTTPErrorResponseBuilder) SetCode(code string) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for SetCode")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(string) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// SetDetails provides a mock function with given fields: details
func (_m *HTTPErrorResponseBuilder) SetDetails(details map[string]interface{}) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(details)

	if len(ret) == 0 {
		panic("no return value specified for SetDetails")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(map[string]interface{}) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// SetMessage provides a mock function with given fields: message
func (_m *HTTPErrorResponseBuilder) SetMessage(message string) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SetMessage")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(string) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// SetStack provides a mock function with given fields: stack
func (_m *HTTPErrorResponseBuilder) SetStack(stack string) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(stack)

	if len(ret) == 0 {
		panic("no return value specified for SetStack")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(string) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(stack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// SetStatus provides a mock function with given fields: status
func (_m *HTTPErrorResponseBuilder) SetStatus(status int) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(int) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// WithDetails provides a mock function with given fields: withDetails
func (_m *HTTPErrorResponseBuilder) WithDetails(withDetails bool) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(withDetails)

	if len(ret) == 0 {
		panic("no return value specified for WithDetails")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(bool) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(withDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// WithStack provides a mock function with given fields: withStack
func (_m *HTTPErrorResponseBuilder) WithStack(withStack bool) httperrorresponse.HTTPErrorResponseBuilder {
	ret := _m.Called(withStack)

	if len(ret) == 0 {
		panic("no return value specified for WithStack")
	}

	var r0 httperrorresponse.HTTPErrorResponseBuilder
	if rf, ok := ret.Get(0).(func(bool) httperrorresponse.HTTPErrorResponseBuilder); ok {
		r0 = rf(withStack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httperrorresponse.HTTPErrorResponseBuilder)
		}
	}

	return r0
}

// NewHTTPErrorResponseBuilder creates a new instance of HTTPErrorResponseBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPErrorResponseBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPErrorResponseBuilder {
	mock := &HTTPErrorResponseBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
