// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	invoker "frisboo-bank/pkg/container/dependencies/invoker"

	mock "github.com/stretchr/testify/mock"

	options "frisboo-bank/pkg/options"
)

// Invoker is an autogenerated mock type for the Invoker type
type Invoker struct {
	mock.Mock
}

// Constructor provides a mock function with no fields
func (_m *Invoker) Constructor() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Constructor")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// IsDependency provides a mock function with no fields
func (_m *Invoker) IsDependency() {
	_m.Called()
}

// Options provides a mock function with no fields
func (_m *Invoker) Options() []options.OptionFn[invoker.Config] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 []options.OptionFn[invoker.Config]
	if rf, ok := ret.Get(0).(func() []options.OptionFn[invoker.Config]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.OptionFn[invoker.Config])
		}
	}

	return r0
}

// NewInvoker creates a new instance of Invoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Invoker {
	mock := &Invoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
