// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	decorator "frisboo-bank/pkg/container/dependencies/decorator"
	hook "frisboo-bank/pkg/container/dependencies/hook"

	invoker "frisboo-bank/pkg/container/dependencies/invoker"

	mock "github.com/stretchr/testify/mock"

	module "frisboo-bank/pkg/container/dependencies/module"

	provider "frisboo-bank/pkg/container/dependencies/provider"
)

// Module is an autogenerated mock type for the Module type
type Module struct {
	mock.Mock
}

// AddDecorators provides a mock function with given fields: decorators
func (_m *Module) AddDecorators(decorators ...decorator.Decorator) module.Module {
	_va := make([]interface{}, len(decorators))
	for _i := range decorators {
		_va[_i] = decorators[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddDecorators")
	}

	var r0 module.Module
	if rf, ok := ret.Get(0).(func(...decorator.Decorator) module.Module); ok {
		r0 = rf(decorators...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.Module)
		}
	}

	return r0
}

// AddHooks provides a mock function with given fields: hooks
func (_m *Module) AddHooks(hooks ...hook.Hooks) module.Module {
	_va := make([]interface{}, len(hooks))
	for _i := range hooks {
		_va[_i] = hooks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddHooks")
	}

	var r0 module.Module
	if rf, ok := ret.Get(0).(func(...hook.Hooks) module.Module); ok {
		r0 = rf(hooks...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.Module)
		}
	}

	return r0
}

// AddInvokers provides a mock function with given fields: invokers
func (_m *Module) AddInvokers(invokers ...invoker.Invoker) module.Module {
	_va := make([]interface{}, len(invokers))
	for _i := range invokers {
		_va[_i] = invokers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddInvokers")
	}

	var r0 module.Module
	if rf, ok := ret.Get(0).(func(...invoker.Invoker) module.Module); ok {
		r0 = rf(invokers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.Module)
		}
	}

	return r0
}

// AddModules provides a mock function with given fields: modules
func (_m *Module) AddModules(modules ...module.Module) module.Module {
	_va := make([]interface{}, len(modules))
	for _i := range modules {
		_va[_i] = modules[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddModules")
	}

	var r0 module.Module
	if rf, ok := ret.Get(0).(func(...module.Module) module.Module); ok {
		r0 = rf(modules...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.Module)
		}
	}

	return r0
}

// AddProviders provides a mock function with given fields: providers
func (_m *Module) AddProviders(providers ...provider.Provider) module.Module {
	_va := make([]interface{}, len(providers))
	for _i := range providers {
		_va[_i] = providers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddProviders")
	}

	var r0 module.Module
	if rf, ok := ret.Get(0).(func(...provider.Provider) module.Module); ok {
		r0 = rf(providers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.Module)
		}
	}

	return r0
}

// Decorators provides a mock function with no fields
func (_m *Module) Decorators() []decorator.Decorator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Decorators")
	}

	var r0 []decorator.Decorator
	if rf, ok := ret.Get(0).(func() []decorator.Decorator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]decorator.Decorator)
		}
	}

	return r0
}

// Hooks provides a mock function with no fields
func (_m *Module) Hooks() []hook.Hooks {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hooks")
	}

	var r0 []hook.Hooks
	if rf, ok := ret.Get(0).(func() []hook.Hooks); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hook.Hooks)
		}
	}

	return r0
}

// Invokers provides a mock function with no fields
func (_m *Module) Invokers() []invoker.Invoker {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Invokers")
	}

	var r0 []invoker.Invoker
	if rf, ok := ret.Get(0).(func() []invoker.Invoker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invoker.Invoker)
		}
	}

	return r0
}

// IsDependency provides a mock function with no fields
func (_m *Module) IsDependency() {
	_m.Called()
}

// Modules provides a mock function with no fields
func (_m *Module) Modules() []module.Module {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modules")
	}

	var r0 []module.Module
	if rf, ok := ret.Get(0).(func() []module.Module); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]module.Module)
		}
	}

	return r0
}

// Name provides a mock function with no fields
func (_m *Module) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Providers provides a mock function with no fields
func (_m *Module) Providers() []provider.Provider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 []provider.Provider
	if rf, ok := ret.Get(0).(func() []provider.Provider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Provider)
		}
	}

	return r0
}

// NewModule creates a new instance of Module. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *Module {
	mock := &Module{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
