// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Numeric is an autogenerated mock type for the Numeric type
type Numeric struct {
	mock.Mock
}

// NewNumeric creates a new instance of Numeric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNumeric(t interface {
	mock.TestingT
	Cleanup(func())
}) *Numeric {
	mock := &Numeric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
