// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OptionFn is an autogenerated mock type for the OptionFn type
type OptionFn[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *OptionFn[T]) Execute(_a0 *T) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*T) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOptionFn creates a new instance of OptionFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptionFn[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *OptionFn[T] {
	mock := &OptionFn[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
