// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	config "frisboo-bank/pkg/http/http_server/adapters/gin/config"

	mock "github.com/stretchr/testify/mock"
)

// Options is an autogenerated mock type for the Options type
type Options[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Options[T]) Execute(_a0 *config.Config) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOptions creates a new instance of Options. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptions[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Options[T] {
	mock := &Options[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
