// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	options "frisboo-bank/pkg/options"

	mock "github.com/stretchr/testify/mock"

	provider "frisboo-bank/pkg/container/dependencies/provider"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// Constructor provides a mock function with no fields
func (_m *Provider) Constructor() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Constructor")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// IsDependency provides a mock function with no fields
func (_m *Provider) IsDependency() {
	_m.Called()
}

// Options provides a mock function with no fields
func (_m *Provider) Options() []options.OptionFn[provider.Config] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 []options.OptionFn[provider.Config]
	if rf, ok := ret.Get(0).(func() []options.OptionFn[provider.Config]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.OptionFn[provider.Config])
		}
	}

	return r0
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
