// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RouteGroup is an autogenerated mock type for the RouteGroup type
type RouteGroup struct {
	mock.Mock
}

// NewRouteGroup creates a new instance of RouteGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouteGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouteGroup {
	mock := &RouteGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
