// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	contracts "frisboo-bank/pkg/http/http_server/contracts"

	mock "github.com/stretchr/testify/mock"
)

// RouteBuilder is an autogenerated mock type for the RouteBuilder type
type RouteBuilder struct {
	mock.Mock
}

// Build provides a mock function with no fields
func (_m *RouteBuilder) Build() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// RegisterGroup provides a mock function with given fields: groupName
func (_m *RouteBuilder) RegisterGroup(groupName string) contracts.RouteBuilder {
	ret := _m.Called(groupName)

	if len(ret) == 0 {
		panic("no return value specified for RegisterGroup")
	}

	var r0 contracts.RouteBuilder
	if rf, ok := ret.Get(0).(func(string) contracts.RouteBuilder); ok {
		r0 = rf(groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.RouteBuilder)
		}
	}

	return r0
}

// RegisterGroupFunc provides a mock function with given fields: groupName, builder
func (_m *RouteBuilder) RegisterGroupFunc(groupName string, builder func(contracts.RouteGroup)) contracts.RouteBuilder {
	ret := _m.Called(groupName, builder)

	if len(ret) == 0 {
		panic("no return value specified for RegisterGroupFunc")
	}

	var r0 contracts.RouteBuilder
	if rf, ok := ret.Get(0).(func(string, func(contracts.RouteGroup)) contracts.RouteBuilder); ok {
		r0 = rf(groupName, builder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.RouteBuilder)
		}
	}

	return r0
}

// RegisterRoutes provides a mock function with given fields: builder
func (_m *RouteBuilder) RegisterRoutes(builder func(interface{})) contracts.RouteBuilder {
	ret := _m.Called(builder)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRoutes")
	}

	var r0 contracts.RouteBuilder
	if rf, ok := ret.Get(0).(func(func(interface{})) contracts.RouteBuilder); ok {
		r0 = rf(builder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.RouteBuilder)
		}
	}

	return r0
}

// UseForGroup provides a mock function with given fields: groupName, middleware
func (_m *RouteBuilder) UseForGroup(groupName string, middleware ...interface{}) contracts.RouteBuilder {
	var _ca []interface{}
	_ca = append(_ca, groupName)
	_ca = append(_ca, middleware...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UseForGroup")
	}

	var r0 contracts.RouteBuilder
	if rf, ok := ret.Get(0).(func(string, ...interface{}) contracts.RouteBuilder); ok {
		r0 = rf(groupName, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.RouteBuilder)
		}
	}

	return r0
}

// NewRouteBuilder creates a new instance of RouteBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouteBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouteBuilder {
	mock := &RouteBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
