// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SignedInteger is an autogenerated mock type for the SignedInteger type
type SignedInteger struct {
	mock.Mock
}

// NewSignedInteger creates a new instance of SignedInteger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignedInteger(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignedInteger {
	mock := &SignedInteger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
