// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsignedInteger is an autogenerated mock type for the UnsignedInteger type
type UnsignedInteger struct {
	mock.Mock
}

// NewUnsignedInteger creates a new instance of UnsignedInteger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsignedInteger(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsignedInteger {
	mock := &UnsignedInteger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
