// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	contracts "frisboo-bank/pkg/waiter/contracts"

	mock "github.com/stretchr/testify/mock"
)

// Waiter is an autogenerated mock type for the Waiter type
type Waiter struct {
	mock.Mock
}

// Add provides a mock function with given fields: hooks
func (_m *Waiter) Add(hooks ...contracts.WaiterHook) {
	_va := make([]interface{}, len(hooks))
	for _i := range hooks {
		_va[_i] = hooks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Cancel provides a mock function with no fields
func (_m *Waiter) Cancel() {
	_m.Called()
}

// Wait provides a mock function with no fields
func (_m *Waiter) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWaiter creates a new instance of Waiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWaiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Waiter {
	mock := &Waiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
