// DO NOT EDIT.
// code generated by goenums v0.4.3 at Jul  4 00:46:34.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -c http_server_type.go

package httpservertype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
)

// HttpServerType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type HttpServerType struct {
	httpServerType
}

// httpServerTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the HttpServerType type.
type httpServerTypesContainer struct {
	UNKNOWN HttpServerType
	GIN     HttpServerType
}

// HttpServerTypes is a main entry point using the HttpServerType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var HttpServerTypes = httpServerTypesContainer{
	UNKNOWN: HttpServerType{
		httpServerType: unknown,
	},
	GIN: HttpServerType{
		httpServerType: gin,
	},
}

// invalidHttpServerType is an invalid sentinel value for HttpServerType
var invalidHttpServerType = HttpServerType{
	httpServerType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (h httpServerTypesContainer) allSlice() []HttpServerType {
	return []HttpServerType{
		HttpServerTypes.GIN,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (h httpServerTypesContainer) All() iter.Seq[HttpServerType] {
	return func(yield func(HttpServerType) bool) {
		for _, v := range h.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseHttpServerType = errors.New("invalid input provided to parse to HttpServerType")

// ParseHttpServerType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseHttpServerType(input any) (HttpServerType, error) {
	switch v := input.(type) {
	case HttpServerType:
		return v, nil
	case string:
		if result := stringToHttpServerType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToHttpServerType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToHttpServerType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToHttpServerType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidHttpServerType, fmt.Errorf("invalid type %T", input)
	}
	return invalidHttpServerType, fmt.Errorf("%w: invalid value %v", ErrParseHttpServerType, input)
}

// httpServerTypesNameMap is a map of enum values to their HttpServerType representation
// It is used to convert string representations of enum values into their HttpServerType representation.
var httpServerTypesNameMap = map[string]HttpServerType{
	"unknown": HttpServerTypes.UNKNOWN,
	"gin":     HttpServerTypes.GIN,
}

// stringToHttpServerType converts a string representation of an enum value into its HttpServerType representation
// It returns a pointer to the HttpServerType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToHttpServerType(s string) *HttpServerType {
	if t, ok := httpServerTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToHttpServerType converts a numeric value to a HttpServerType
// It returns a pointer to the HttpServerType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToHttpServerType[T number](num T) *HttpServerType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(HttpServerTypes.allSlice()) {
		return nil
	}
	result := HttpServerTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveHttpServerTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveHttpServerTypes(f func(HttpServerType)) {
	for _, p := range HttpServerTypes.allSlice() {
		f(p)
	}
}

// validHttpServerTypes is a map of enum values to their validity
var validHttpServerTypes = map[HttpServerType]bool{
	HttpServerTypes.UNKNOWN: false,
	HttpServerTypes.GIN:     true,
}

// IsValid checks whether the HttpServerTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (h HttpServerType) IsValid() bool {
	return validHttpServerTypes[h]
}

// MarshalJSON implements the json.Marshaler interface for HttpServerType.
// It returns the JSON representation of the enum value as a byte slice.
func (h HttpServerType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for HttpServerType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (h *HttpServerType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newh, err := ParseHttpServerType(b)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for HttpServerType.
// It returns the string representation of the enum value as a byte slice
func (h HttpServerType) MarshalText() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for HttpServerType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (h *HttpServerType) UnmarshalText(b []byte) error {
	newh, err := ParseHttpServerType(b)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// Scan implements the database/sql.Scanner interface for HttpServerType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (h *HttpServerType) Scan(value any) error {
	newh, err := ParseHttpServerType(value)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// Value implements the database/sql/driver.Valuer interface for HttpServerType.
// It returns the string representation of the enum value.
func (h HttpServerType) Value() (driver.Value, error) {
	return h.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for HttpServerType.
// It returns the binary representation of the enum value as a byte slice.
func (h HttpServerType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for HttpServerType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (h *HttpServerType) UnmarshalBinary(b []byte) error {
	newh, err := ParseHttpServerType(b)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for HttpServerType.
// It returns the string representation of the enum value.
func (h HttpServerType) MarshalYAML() ([]byte, error) {
	return []byte(h.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (h *HttpServerType) UnmarshalYAML(b []byte) error {
	newh, err := ParseHttpServerType(b)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

type float interface {
	float32 | float64
}
type integer interface {
	int | int8 | int16 | int32 | int64 | uint | uint8 | uint16 | uint32 | uint64 | uintptr
}
type number interface {
	integer | float
}

// httpservertypeNames is a constant string slice containing all enum values cononical absolute names
const httpservertypeNames = "unknowngin"

// httpservertypeNamesMap is a map of enum values to their canonical absolute
// name positions within the httpservertypeNames string slice
var httpservertypeNamesMap = map[HttpServerType]string{
	HttpServerTypes.UNKNOWN: httpservertypeNames[0:7],
	HttpServerTypes.GIN:     httpservertypeNames[7:10],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (h HttpServerType) String() string {
	if str, ok := httpservertypeNamesMap[h]; ok {
		return str
	}
	return fmt.Sprintf("httpservertype(%d)", h.httpServerType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[unknown]
	_ = x[gin-1]
}
