// DO NOT EDIT.
// code generated by goenums v0.4.3 at Jul  3 19:10:53.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f encoding_type.go

package encodingtype

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// EncodingType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type EncodingType struct {
	encodingType
}

// encodingTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the EncodingType type.
type encodingTypesContainer struct {
	UNKNOWN EncodingType
	JSON    EncodingType
	TEXT    EncodingType
}

// EncodingTypes is a main entry point using the EncodingType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var EncodingTypes = encodingTypesContainer{
	UNKNOWN: EncodingType{
		encodingType: unknown,
	},
	JSON: EncodingType{
		encodingType: json,
	},
	TEXT: EncodingType{
		encodingType: text,
	},
}

// invalidEncodingType is an invalid sentinel value for EncodingType
var invalidEncodingType = EncodingType{
	encodingType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e encodingTypesContainer) allSlice() []EncodingType {
	return []EncodingType{
		EncodingTypes.JSON,
		EncodingTypes.TEXT,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e encodingTypesContainer) All() iter.Seq[EncodingType] {
	return func(yield func(EncodingType) bool) {
		for _, v := range e.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseEncodingType = errors.New("invalid input provided to parse to EncodingType")

// ParseEncodingType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseEncodingType(input any) (EncodingType, error) {
	switch v := input.(type) {
	case EncodingType:
		return v, nil
	case string:
		if result := stringToEncodingType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToEncodingType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToEncodingType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToEncodingType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidEncodingType, fmt.Errorf("invalid type %T", input)
	}
	return invalidEncodingType, fmt.Errorf("%w: invalid value %v", ErrParseEncodingType, input)
}

// encodingTypesNameMap is a map of enum values to their EncodingType representation
// It is used to convert string representations of enum values into their EncodingType representation.
var encodingTypesNameMap = map[string]EncodingType{
	"unknown": EncodingTypes.UNKNOWN,
	"json":    EncodingTypes.JSON,
	"text":    EncodingTypes.TEXT,
}

// stringToEncodingType converts a string representation of an enum value into its EncodingType representation
// It returns a pointer to the EncodingType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToEncodingType(s string) *EncodingType {
	if t, ok := encodingTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToEncodingType converts a numeric value to a EncodingType
// It returns a pointer to the EncodingType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToEncodingType[T constraints.Integer | constraints.Float](num T) *EncodingType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(EncodingTypes.allSlice()) {
		return nil
	}
	result := EncodingTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveEncodingTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveEncodingTypes(f func(EncodingType)) {
	for _, p := range EncodingTypes.allSlice() {
		f(p)
	}
}

// validEncodingTypes is a map of enum values to their validity
var validEncodingTypes = map[EncodingType]bool{
	EncodingTypes.UNKNOWN: false,
	EncodingTypes.JSON:    true,
	EncodingTypes.TEXT:    true,
}

// IsValid checks whether the EncodingTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (e EncodingType) IsValid() bool {
	return validEncodingTypes[e]
}

// MarshalJSON implements the json.Marshaler interface for EncodingType.
// It returns the JSON representation of the enum value as a byte slice.
func (e EncodingType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for EncodingType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (e *EncodingType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newe, err := ParseEncodingType(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for EncodingType.
// It returns the string representation of the enum value as a byte slice
func (e EncodingType) MarshalText() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EncodingType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EncodingType) UnmarshalText(b []byte) error {
	newe, err := ParseEncodingType(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Scan implements the database/sql.Scanner interface for EncodingType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (e *EncodingType) Scan(value any) error {
	newe, err := ParseEncodingType(value)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Value implements the database/sql/driver.Valuer interface for EncodingType.
// It returns the string representation of the enum value.
func (e EncodingType) Value() (driver.Value, error) {
	return e.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for EncodingType.
// It returns the binary representation of the enum value as a byte slice.
func (e EncodingType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for EncodingType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EncodingType) UnmarshalBinary(b []byte) error {
	newe, err := ParseEncodingType(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for EncodingType.
// It returns the string representation of the enum value.
func (e EncodingType) MarshalYAML() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (e *EncodingType) UnmarshalYAML(b []byte) error {
	newe, err := ParseEncodingType(b)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// encodingtypeNames is a constant string slice containing all enum values cononical absolute names
const encodingtypeNames = "unknownjsontext"

// encodingtypeNamesMap is a map of enum values to their canonical absolute
// name positions within the encodingtypeNames string slice
var encodingtypeNamesMap = map[EncodingType]string{
	EncodingTypes.UNKNOWN: encodingtypeNames[0:7],
	EncodingTypes.JSON:    encodingtypeNames[7:11],
	EncodingTypes.TEXT:    encodingtypeNames[11:15],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (e EncodingType) String() string {
	if str, ok := encodingtypeNamesMap[e]; ok {
		return str
	}
	return fmt.Sprintf("encodingtype(%d)", e.encodingType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[unknown]
	_ = x[json-1]
	_ = x[text-2]
}
